const knowledgeBase = {
  "what is gravity": "Gravity pulls objects toward each other.",
  "what is photosynthesis": "Plants use sunlight to make food.",
  "who discovered gravity": "Sir Isaac Newton.",
  "what is the capital of france": "Paris.",
  "what is the boiling point of water": "100°C or 212°F.",
  "what is the largest planet": "Jupiter.",
  "who wrote hamlet": "William Shakespeare.",
  "what is the square root of 64": "8.",
  "what is the formula for area of a circle": "Area = π × radius²",
  "what is the capital of india": "New Delhi.",
  "who painted the mona lisa": "Leonardo da Vinci.",
  "how many bones are in the human body": "206 bones.",
  "what is the largest ocean": "The Pacific Ocean.",
  "what is the main source of energy for earth": "The Sun.",
  "what is the freezing point of water": "0°C or 32°F.",
  "what is the capital of japan": "Tokyo.",
  "what is the chemical symbol for oxygen": "O.",
  "what is the hardest natural substance": "Diamond.",
  "what is the largest mammal": "The blue whale.",
  "what is democracy": "A system of government where citizens vote to elect leaders.",
  "what is a noun": "A word that names a person, place, or thing.",
  "what is a verb": "A word that shows action.",
  "what is a triangle": "A shape with three sides.",
  "what is area": "The space inside a shape.",
  "what is volume": "The space inside a 3D object.",
  "what is matter": "Anything that has mass and takes up space.",
  "what is an atom": "The smallest unit of matter.",
  "what is a cell": "The basic unit of life.",
  "what is digestion": "The process of breaking down food.",
  "what is respiration": "Using oxygen to release energy.",
  "what is electricity": "Energy that powers devices.",
  "what is a computer": "A machine that processes data.",
  "what is the internet": "A global network of computers.",
  "what is recycling": "Turning waste into new products.",
  "what is pollution": "Harmful substances in the environment.",
  "what is climate change": "Long-term changes in Earth's climate.",
  "what is a habitat": "The natural home of an organism.",
  "what is adaptation": "A change that helps survival.",
  "what is extinction": "When a species dies out.",
  "what is a food chain": "Energy transfer between organisms.",
  "what is a producer": "An organism that makes its own food.",
  "what is a consumer": "An organism that eats other organisms."
    "what is 1+1": "2",
  "what is 2+2": "4",
  "what is 10-4": "6",
  "what is 5×6": "30",
  "what is 20÷4": "5",
  "what is 12+15": "27",
  "what is 100-75": "25",
  "what is 9×9": "81",
  "what is 81÷9": "9",
  "what is 25+36": "61",
  "what is 40÷5": "8",
  "what is 1/2 + 1/4": "3/4",
  "what is 3/4 - 1/4": "1/2",
  "what is 2/3 × 3/5": "2/5",
  "what is 1/2 ÷ 1/4": "2",
  "convert 0.75 to fraction": "3/4",
  "what is 0.1 + 0.2": "0.3",
  "what is 1.5 × 2": "3",
  "what is 3.6 ÷ 0.6": "6",
  "convert 1/5 to decimal": "0.2",
  "what is 0.25 + 0.75": "1",
  "how many sides does a hexagon have": "6",
  "how many degrees in a triangle": "180°",
  "what is the perimeter of a square with side 5cm": "20 cm",
  "what is the area of a rectangle with length 6 and width 4": "24",
  "what is the area of a circle with radius 3": "28.26 (π ≈ 3.14)",
  "what is the volume of a cube with side 4": "64",
  "what is 7×7": "49",
  "what is 8×8": "64",
  "what is 9×8": "72",
  "what is 11×11": "121",
  "what is 12×12": "144",
  "what is 1000÷10": "100",
  "what is 1000÷100": "10",
  "what is 1000÷1000": "1",
  "what is 0.5 + 0.25": "0.75",
  "what is 0.5 × 0.5": "0.25",
  "what is 0.5 ÷ 0.1": "5",
  "what is 0.1 × 0.1": "0.01",
  "what is 0.2 × 0.2": "0.04",
  "what is 0.3 × 0.3": "0.09",
  "what is 0.4 × 0.4": "0.16",
  "what is 0.5 × 0.5": "0.25",
  "what is 0.6 × 0.6": "0.36",
  "what is 0.7 × 0.7": "0.49",
  "what is 0.8 × 0.8": "0.64",
  "what is 0.9 × 0.9": "0.81",
  "what is 1 × 1": "1",
  "what is 2 × 2": "4",
  "what is 3 × 3": "9",
  "what is 4 × 4": "16",
  "what is 5 × 5": "25",
  "what is 6 × 6": "36",
  "what is 7 × 7": "49",
  "what is 8 × 8": "64",
  "what is 9 × 9": "81",
  "what is 10 × 10": "100"
  };

